package com.onebooming.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_create
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_modified
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.creator_id
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.commentSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Integer commentsum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.browseSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Integer browsesum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.thumbsupSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private Integer thumbsupsum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.tag
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_create
     *
     * @return the value of question.gmt_create
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_create
     *
     * @param gmtCreate the value for question.gmt_create
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_modified
     *
     * @return the value of question.gmt_modified
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_modified
     *
     * @param gmtModified the value for question.gmt_modified
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.creator_id
     *
     * @return the value of question.creator_id
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.creator_id
     *
     * @param creatorId the value for question.creator_id
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.commentSum
     *
     * @return the value of question.commentSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Integer getCommentsum() {
        return commentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.commentSum
     *
     * @param commentsum the value for question.commentSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setCommentsum(Integer commentsum) {
        this.commentsum = commentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.browseSum
     *
     * @return the value of question.browseSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Integer getBrowsesum() {
        return browsesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.browseSum
     *
     * @param browsesum the value for question.browseSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setBrowsesum(Integer browsesum) {
        this.browsesum = browsesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.thumbsupSum
     *
     * @return the value of question.thumbsupSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public Integer getThumbsupsum() {
        return thumbsupsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.thumbsupSum
     *
     * @param thumbsupsum the value for question.thumbsupSum
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setThumbsupsum(Integer thumbsupsum) {
        this.thumbsupsum = thumbsupsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.tag
     *
     * @return the value of question.tag
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.tag
     *
     * @param tag the value for question.tag
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbg.generated Sun Dec 01 14:28:57 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public void setGmtModify(long currentTimeMillis) {
    }
}